function [plot_grf,frames_of_impact_grf,last_frame_grf] = detect_impact_forceplate(acq,threshold_forceplate_impact,treshold_time)
analogs = btkGetAnalogs(acq); % will extract the values of all the analogs entry given by qualisys
ratio = btkGetAnalogSampleNumberPerFrame(acq); %will compute the ratio between the sampling frequency of the analogs entry and of the cameras. The data is not sampled doxn in this case as both the force plates and the optogait are sampled at 2000Hz
labels = fieldnames(analogs);
grf = btkGetGroundReactionWrenches(acq); %will extract the values of wrenches. May generat a warning message because of the frame used to determine the position of the plate in space, but it is not a problem as moments are not computed
grf1=grf(1).F(:,[3]); %creates a vector with only the Z components (3rd col) of the force for the 1st plate
plot_grf=plot(grf1); %only a test to assure the correct data have been extracted
j=1;
i=1;
last_frame_grf=size(grf1,1);
while i<size(grf1,1)
    if grf1(i)>threshold_forceplate_impact  %If the value is higher than the given threshold, it is considered as an impact
        frames_of_impact_grf(j)=i;  %stor the frame of impact
        j=j+1;
        i=i+treshold_time;  %delay to make sure not to detect the vibrations generated by the impact as an event
    end
    i=i+1;
end
